config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/about"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "home", to: "pages#home"
  get "about", to: "pages#about"

  # Defines the root path route ("/")
  root "pages#home"

  resources :stocks, only: [:index, :show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
require "json"
require "net/http"

class Stock < ApplicationRecord
  validates :ticker, presence: true
  validates :name, presence: true
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.new_lookup(ticker_symbol)
    uri = URI.parse("https://economia.awesomeapi.com.br/last/#{ticker_symbol}")
    begin
      response = Net::HTTP.get_response(uri)
      data = JSON.parse(response.body)[ticker_symbol.delete('-')]
      if data
        new(
          ticker: ticker_symbol,
          name: data['name'],
          last_price: data['ask']
        )
      else
        nil
      end
    rescue JSON::ParserError, StandardError => e
      Rails.logger.error("Error fetching stock data for #{ticker_symbol}: #{e.message}")
      nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks

  # Include default Devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Check if the user can track the stock based on the ticker symbol
  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  # Check if the user is under the stock limit (e.g., 10 stocks)
  def under_stock_limit?
    stocks.count < 10
  end

  # Check if the user is already tracking the stock
  def stock_already_tracked?(ticker_symbol)
    stock = Stock.find_by(ticker: ticker_symbol)
    stocks.where(id: stock.id).exists? if stock
  end
  
  def get_name
    if name.present?
      name
    elsif email.present?
      email
    else
      "anonymous"
    end
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  # Permit the `name` parameter along with other Devise parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :find_or_create_stock, only: [:create, :show]
  before_action :authenticate_user!

  def show
  end

  def new    
  end
  
  def index
    @tracked_stocks = current_user.stocks.order(created_at: :desc)
  end

  def create
    if @stock.present?
      if current_user.can_track_stock?(@stock.ticker)
        if @stock.save
          current_user.stocks << @stock
          redirect_to stocks_path, notice: "#{@stock.ticker} was successfully added to your portfolio."
        else
          redirect_to stocks_path, alert: 'Failed to save stock.'
        end
      else
        redirect_to stocks_path, alert: 'You are already tracking this stock or have reached your limit.'
      end
    else
      redirect_to stocks_path, alert: 'Failed to add stock. Ensure ticker is valid.'
    end
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = current_user.user_stocks.find_by(stock_id: stock.id)
    if user_stock
      user_stock.destroy
      flash[:notice] = "#{stock.ticker} was successfully removed from your portfolio."
    else
      flash[:alert] = "#{stock.ticker} could not be found in your portfolio."
    end
    redirect_to stocks_path
  end


  private

  def find_or_create_stock
    @stock = Stock.check_db(params[:ticker]) || Stock.new_lookup(params[:ticker])
    if @stock.present? && !@stock.persisted?
      @stock.save
    end
  end

  def stock_params
    params.permit(:ticker)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user, options = { size: 40 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size] # Ensure size is taken from options

    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=identicon"
    
    # Conditional Logic: Fallback to email if name is not present
    image_tag(gravatar_url, alt: user.name.presence || user.email, class: "gravatar rounded-circle", style: "width: #{size}px; height: #{size}px;")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>        
          <li class="nav-item">
            <%= link_to 'My Portfolio', stocks_path, class: "nav-link" %>
          </li>
        <% end %>
       </ul>

      <!-- Left-aligned buttons -->
      <div class="d-flex align-items-center ms-auto">
        <% if user_signed_in? %>
          <%= button_to "Log Out", destroy_user_session_path, class: "btn btn-outline-danger me-2", method: :delete %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-primary me-2' %>
          <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-outline-success me-2' %>
        <% end %>
      </div>

      <!-- Right-aligned user profile section -->
      <% if user_signed_in? %>
      <div class="d-flex align-items-center">
        <!-- Use the Gravatar image for the profile picture -->
        <%= gravatar_for(current_user, size: 40) %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name.presence || current_user.email %>
          </a>
          <ul class="dropdown-menu  dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
            <li><%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: :delete %></li>
          </ul>
        </li>
      </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Finance Tracker App 2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Prevent InstantClick - https://github.com/hotwired/turbo/pull/1101-->
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <%= yield :head %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>  
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages'%>
    <main>      
      <div class="container">        
        <%= yield %>
      </div>
    </main>
     <!-- Bootstrap 5 JS Bundle -->
    <!-- JavaScript tag-->
      <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js', 'data-turbolinks-track': 'reload' %>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<section class="about">
  <div class="container">
    <h2>About Me</h2>
    <p>
      Hi, I'm <strong>Gilberto Jr</strong>, a passionate Full Stack Developer with a degree in <strong>Computer Engineering</strong>.
      I specialize in building robust, scalable web applications using the latest technologies. My work spans various projects 
      that leverage both front-end and back-end development skills, ensuring complete and efficient solutions.
    </p>
    <p>
      Feel free to explore my projects and contributions on my 
      <a href="#" target="_blank">GitHub repository</a>. You'll find a range of tools, apps, and experiments that showcase 
      my approach to problem-solving and development.
    </p>
    <p>
      Whether you're here to explore my work or collaborate, I’m always excited to connect with like-minded developers and innovators!
    </p>
  </div>
</section>

app/views/pages/home.html.erb
<div>
  <div class="jumbotron">
    <h1 class="display-7">Welcome to J3 Finance Tracker App!</h1>
  </div>
  <div class="lead">
        <h3 class="lead">This is a market-leading crypto portfolio, built to help you save money, plan for the future, and see all your investments in one place.</h3>
    
        <%# <a class="btn btn-primary btn-lg" href="#" role="button">Go To My Portfolio</a><br> %>
        
        <%= link_to 'Go To My Portfolio', stocks_path, class: "btn btn-primary btn-lg" %>
        
        <%# link_to replaces the <a> tag completely, so you don't need to write the <a> tag manually. %>
        <%# 'Go To My Portfolio' is the text that will appear on the button. %>
        <%# stocks_path is the URL/path you want the link to navigate to. %>
        <%# class: "btn btn-primary btn-lg" adds Bootstrap styling to make the link look like a button. %>  
  </div>
</div>

app/views/stocks/_form.html.erb
<!-- app/views/stocks/index.html.erb -->
    <%= form_with(url: stocks_path, method: :post, local: true) do |form| %>
      <div class="row">
        <div class="col-md-10">
          <%= form.text_field :ticker, placeholder: 'Stock Ticker', class: 'form-control' %>
        </div>
        <div class="col-md-2">
          <%= form.submit "Search", class: "btn btn-primary w-100" %>
        </div>
      </div>
    <% end %>

app/views/stocks/_list.html.erb
<!-- Table Section -->
<div class="row">
  <div class="col-md-12">
    <% if @tracked_stocks.any? %>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th scope="col">Ticker</th>
              <th scope="col">Name</th>
              <th scope="col">Price</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
          <% @tracked_stocks.each_with_index do |stock, index| %>
            <tr <%= 'class=table-success' if index == 0 %>>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <td>
                <% if current_user.stock_already_tracked?(stock.ticker) %>
                  <%= link_to "Remove", stock_path(stock), 
                              data: { "turbo-method": "delete", "turbo-confirm": "Are you sure?" }, 
                              class: "btn btn-sm btn-warning" %>
                <% else %>
                  <%= link_to "Add to Portfolio", user_stocks_path(ticker: stock.ticker), 
                              class: "btn btn-sm btn-success", 
                              data: { "turbo-method": :post } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    <% else %>
      <p class="text-center">You have not added any stocks yet. </p>
      <p class="text-center">See the <a href="https://economia.awesomeapi.com.br/xml/available">full list</a> of combinations (Currency Codes: USD-BRL, USD-BRLT, CAD-BRL, EUR-BRL).</p>
    <% end %>
  </div>
</div>

app/views/stocks/index.html.erb
<!-- app/views/stocks/index.html.erb -->
<div class="container py-4">
  <!-- Header Section -->
  <h1 class="display-4 mb-3">My Portfolio</h1>

  <!-- Search Form -->
  <div class="mb-3">
    <h3 class="mb-3">Search Currency Quotation</h3>
    <%= render 'form' %>
  </div>

  <!-- Table Section -->
  <div>
    <%= render 'list' %>
  </div>
</div>